version: 0.0.{build}

branches:
  only:
    - master

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

before_build: nuget restore

build:
  project: EFeature.sln

after_test:
  - ps: .\deployment\package.ps1

artifacts:
  - path: src\EFeature\bin\Release\EFeature.dll
    name: EFeature.dll
  - path: '**\EFeature*.nupkg'